use_frameworks!

platform :ios, '15.0' 
install! 'cocoapods', :disable_input_output_paths => true

target 'TQIExtract_Example' do
  pod 'TQIExtract', :path => '../'

  target 'TQIExtract_Tests' do
    inherit! :search_paths

    
  end
end